### ISSUE TITLE
Detection of special edition cards

### ISSUE THREAD

**Issue by christianrickert** [hugopeixoto/ptcg-detection#1]
Hi Hugo,

Awesome job and a [great talk](https://www.youtube.com/watch?v=BLy_YF4nmqQ)! -

I was wondering, if you've experimented with a polarization filter (in front of your camera) to improve the detection rate of highly reflective or iridescent cards?

Chris

**Comment by hugopeixoto** [comment]
Hey, thanks for watching :)

I haven't, but someone suggested the same during Q&A, so I'm currently waiting for my order to arrive.

(I edited your comment to use the individual video URL instead of the livestream one)
